[2019-10-08 18:27:59,164] {{models.py:1361}} INFO - Dependencies all met for <TaskInstance: housing_price_prediction_training.training_data_processing 2019-10-08T17:43:32.113975+00:00 [queued]>
[2019-10-08 18:27:59,186] {{models.py:1361}} INFO - Dependencies all met for <TaskInstance: housing_price_prediction_training.training_data_processing 2019-10-08T17:43:32.113975+00:00 [queued]>
[2019-10-08 18:27:59,186] {{models.py:1573}} INFO - 
--------------------------------------------------------------------------------
Starting attempt 14 of 15
--------------------------------------------------------------------------------

[2019-10-08 18:27:59,217] {{models.py:1595}} INFO - Executing <Task(PythonOperator): training_data_processing> on 2019-10-08T17:43:32.113975+00:00
[2019-10-08 18:27:59,218] {{base_task_runner.py:118}} INFO - Running: ['bash', '-c', 'airflow run housing_price_prediction_training training_data_processing 2019-10-08T17:43:32.113975+00:00 --job_id 17 --raw -sd DAGS_FOLDER/housing_price_prediction_training.py --cfg_path /tmp/tmpjxbf54_3']
[2019-10-08 18:27:59,750] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing [2019-10-08 18:27:59,750] {{settings.py:174}} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
[2019-10-08 18:27:59,954] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing [2019-10-08 18:27:59,953] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2019-10-08 18:28:00,381] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing [2019-10-08 18:28:00,380] {{models.py:271}} INFO - Filling up the DagBag from /usr/local/airflow/dags/housing_price_prediction_training.py
[2019-10-08 18:28:00,434] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing [2019-10-08 18:28:00,434] {{cli.py:484}} INFO - Running <TaskInstance: housing_price_prediction_training.training_data_processing 2019-10-08T17:43:32.113975+00:00 [running]> on host 63734ffeb1b4
[2019-10-08 18:28:00,513] {{logging_mixin.py:95}} INFO - e1af309d-203f-4d44-a55b-d5635016c946
[2019-10-08 18:28:00,514] {{logging_mixin.py:95}} INFO - http://192.168.0.102:5001/check/e1af309d-203f-4d44-a55b-d5635016c946
[2019-10-08 18:28:00,547] {{models.py:1760}} ERROR - ml_automation.core.DataProcessor TypeError string indices must be integersTraceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ml_automation/core/DataProcessor.py", line 18, in DataProcessor
    util.getValFromDict('raw_file_paths', raw_request))
  File "/usr/local/lib/python3.6/site-packages/common_utils/ServiceHelper.py", line 210, in getValFromDict
    if name in data and data[name] is not None:
TypeError: string indices must be integers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 95, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 100, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/housing_price_prediction_training.py", line 42, in training_data_processing
    print(invoke_endpoint(training_data_processing_config))
  File "/usr/local/airflow/dags/housing_price_prediction_training.py", line 36, in invoke_endpoint
    raise Exception(response["Exception"])
Exception: ml_automation.core.DataProcessor TypeError string indices must be integersTraceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ml_automation/core/DataProcessor.py", line 18, in DataProcessor
    util.getValFromDict('raw_file_paths', raw_request))
  File "/usr/local/lib/python3.6/site-packages/common_utils/ServiceHelper.py", line 210, in getValFromDict
    if name in data and data[name] is not None:
TypeError: string indices must be integers

[2019-10-08 18:28:00,551] {{models.py:1783}} INFO - Marking task as UP_FOR_RETRY
[2019-10-08 18:28:00,608] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing Traceback (most recent call last):
[2019-10-08 18:28:00,608] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     args.func(args)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     return f(*args, **kwargs)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 490, in run
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     _run(args, dag, ti)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 406, in _run
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     pool=args.pool,
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     return func(*args, **kwargs)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     result = task_copy.execute(context=context)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 95, in execute
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     return_value = self.execute_callable()
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 100, in execute_callable
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/airflow/dags/housing_price_prediction_training.py", line 42, in training_data_processing
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     print(invoke_endpoint(training_data_processing_config))
[2019-10-08 18:28:00,609] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/airflow/dags/housing_price_prediction_training.py", line 36, in invoke_endpoint
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     raise Exception(response["Exception"])
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing Exception: ml_automation.core.DataProcessor TypeError string indices must be integersTraceback (most recent call last):
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/ml_automation/core/DataProcessor.py", line 18, in DataProcessor
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     util.getValFromDict('raw_file_paths', raw_request))
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing   File "/usr/local/lib/python3.6/site-packages/common_utils/ServiceHelper.py", line 210, in getValFromDict
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing     if name in data and data[name] is not None:
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing TypeError: string indices must be integers
[2019-10-08 18:28:00,610] {{base_task_runner.py:101}} INFO - Job 17: Subtask training_data_processing 
[2019-10-08 18:28:04,206] {{logging_mixin.py:95}} INFO - [2019-10-08 18:28:04,205] {{jobs.py:2627}} INFO - Task exited with return code 1
